"""
Integration Test 5: VerifyTool — cross-validates CSV, Excel, and Google Sheets.

Prerequisites:
  - A real CSV file (auto-generated by this test)
  - A real XLSX file (auto-generated by ExcelTool within this test)
  - credentials/service_account.json present
  - GOOGLE_SHEET_ID in .env pointing to a live spreadsheet with data already uploaded
    OR this test will upload fresh data first using SheetsTool.

Verifies:
  - All three targets are readable
  - Row counts match across CSV, XLSX, and Google Sheet
  - all_match = True
  - artifact_updates() returns verification_passed=True
"""

import os
import sys
import pathlib

sys.path.insert(0, ".")

from dotenv import load_dotenv
load_dotenv()

GOOGLE_SHEET_ID = os.environ.get("GOOGLE_SHEET_ID", "")
CREDS_PATH = pathlib.Path(os.environ.get("GOOGLE_CREDENTIALS_PATH", "credentials/service_account.json"))

if not CREDS_PATH.exists():
    print("\n  [SKIP] credentials/service_account.json not found.")
    sys.exit(0)
if not GOOGLE_SHEET_ID or GOOGLE_SHEET_ID == "your_spreadsheet_id_here":
    print("\n  [SKIP] GOOGLE_SHEET_ID not configured in .env")
    sys.exit(0)


def ok(msg):  print(f"  [PASS] {msg}")
def fail(msg): print(f"  [FAIL] {msg}"); sys.exit(1)
def section(t): print(f"\n{'='*55}\n  {t}\n{'='*55}")


section("INTEGRATION 5: VerifyTool (full cross-validation)")

NUM_ROWS = 20

# ── Step 1: Generate CSV ──────────────────────────────────────────────────────
print("\n  Step 1: Generating source CSV...")
from src.tools.csv_generator.tool import CSVGeneratorTool

csv_result = CSVGeneratorTool().run({"num_rows": NUM_ROWS, "output_dir": "output"})
if not csv_result.success:
    fail(f"CSV generation failed: {csv_result.error}")
csv_path = csv_result.data.csv_path
ok(f"CSV: {csv_path}")

# ── Step 2: Excel import ──────────────────────────────────────────────────────
print("\n  Step 2: Importing to Excel...")
from src.tools.excel_tool.tool import ExcelTool

excel_result = ExcelTool().run({"csv_path": csv_path, "output_dir": "output"})
if not excel_result.success:
    fail(f"Excel import failed: {excel_result.error}")
xlsx_path = excel_result.data.xlsx_path
ok(f"XLSX: {xlsx_path}")

# ── Step 3: Upload to Sheets ──────────────────────────────────────────────────
print("\n  Step 3: Uploading to Google Sheets...")
from src.tools.sheets_tool.tool import SheetsTool

sheets_result = SheetsTool().run({
    "csv_path": csv_path,
    "title": "Employee Data - Verify Integration Test",
})
if not sheets_result.success:
    fail(f"Sheets upload failed: {sheets_result.error}")
sheet_id = sheets_result.data.spreadsheet_id
ok(f"Sheet ID: {sheet_id}")

# ── Step 4: Run VerifyTool ────────────────────────────────────────────────────
print("\n  Step 4: Running VerifyTool cross-validation...")
from src.tools.verify_tool.tool import VerifyTool

verify_result = VerifyTool().run({
    "csv_path": csv_path,
    "xlsx_path": xlsx_path,
    "sheet_id": sheet_id,
})

if not verify_result.success:
    fail(f"VerifyTool itself failed: {verify_result.error}")
ok(f"VerifyTool ran successfully in {verify_result.duration_seconds}s")

data = verify_result.data
print(f"\n  Row counts — CSV: {data.csv_rows}  XLSX: {data.xlsx_rows}  Sheets: {data.sheet_rows}")
print(f"  all_match = {data.all_match}")
print(f"  Summary: {data.summary}")

if not data.all_match:
    fail(f"Verification FAILED: row counts do not match!")
ok("all_match = True — all targets in sync")

if data.csv_rows != NUM_ROWS:
    fail(f"csv_rows expected {NUM_ROWS}, got {data.csv_rows}")
ok(f"csv_rows = {data.csv_rows}")

if data.xlsx_rows != NUM_ROWS:
    fail(f"xlsx_rows expected {NUM_ROWS}, got {data.xlsx_rows}")
ok(f"xlsx_rows = {data.xlsx_rows}")

if data.sheet_rows != NUM_ROWS:
    fail(f"sheet_rows expected {NUM_ROWS}, got {data.sheet_rows}")
ok(f"sheet_rows = {data.sheet_rows}")

# ── Step 5: artifact_updates() ────────────────────────────────────────────────
updates = verify_result.data.artifact_updates()
if updates.get("verification_passed") is not True:
    fail(f"artifact_updates() should have verification_passed=True, got: {updates}")
ok("artifact_updates() returns verification_passed=True")

print("\n  [INTEGRATION 5 PASSED]")
